# Generated by Django 3.1.7 on 2021-03-15 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperPowersModel',
            fields=[
                ('id_superpowers', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('superheroe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superinfo.superinformation')),
            ],
        ),
    ]
