# Generated by Django 3.1.7 on 2021-03-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperInformation',
            fields=[
                ('id_superheroe', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=3)),
                ('sex', models.CharField(max_length=20)),
            ],
        ),
    ]
