# Generated by Django 3.1.7 on 2021-03-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superinformation',
            name='id_superheroe',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
