# Generated by Django 3.1.7 on 2021-03-15 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superinfo', '0002_auto_20210314_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superinformation',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
